services:
  engine:
    build: 
      context: ./engine
    ports:
      - '8000:8000'
    environment:
      - BLOCKCHAIN_URL=http://blockchain:3000 
    depends_on:
      - blockchain
    networks:
      - symbio-net

  frontend:
    build:
      context: ./frontend
    ports:
      - '3001:3000' 
    environment:
      - NEXT_PUBLIC_API_URL=http://engine:8000 
    depends_on:
      - engine
    networks:
      - symbio-net

  blockchain:
    build: 
      context: ./blockchain
    container_name: symbio-link-blockchain
    ports:
      - '4000:4000' 
    networks:
      - symbio-net

networks:
  symbio-net:
    driver: bridge